[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from   = "/shopify-proxy/*"
  to     = "/.netlify/functions/shopify-proxy/:splat"
  status = 200
  force  = true
